# Generated by Django 4.0.5 on 2022-07-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('dueño', models.CharField(max_length=60)),
                ('tipoDeAnimal', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SpaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('reserva', models.DateField()),
                ('pago', models.BooleanField()),
            ],
        ),
    ]
